{
 "title": "Time Respond Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests Per Second",
   "type": "timeseries",
   "description": "Total incoming requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(minitwit_http_responses_total[5m]))",
     "legendFormat": "Total HTTP RPS"
    }
   ]
  },
  {
   "title": "Application status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"itu-minittwit-app\"}",
     "legendFormat": "Application Status"
    }
   ]
  },
  {
   "title": "Time Respond (95th Percentile)",
   "type": "timeseries",
   "description": "95th percentile of response times across all endpoints",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(minitwit_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "P95 Response Time"
    }
   ]
  }
 ]
}