x-syslog-logging: &syslog_logging
  driver: syslog
  options:
    syslog-address: ${SYSLOG_ADDRESS:-udp://127.0.0.1:5514}
    tag: "{{.Name}}"
    syslog-format: rfc5424micro

services:
#  dbserver:
#    image: ${DOCKER_USERNAME}/dbminitwitimage:latest
#    restart: unless-stopped
#    environment:
##      - MONGO_INITDB_DATABASE=test
#      - MONGO_URI=mongodb+srv://${DIGITAL_OCEAN_DATABASE_USERNAME}:${DIGITAL_OCEAN_DATABASE_PWD}@minitwit-dbserver-1-77977c42.mongo.ondigitalocean.com/${DIGITAL_OCEAN_DATABASE_NAME}?tls=true&authSource=admin
#    networks:
#      - minitwit-network
#    volumes:
#      - minitwit_cloud_data:/data/db
#    healthcheck:
#      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
#      interval: 60s
#      timeout: 10s
#      retries: 5
#      start_period: 90s

  webserver:
    image: ${DOCKER_USERNAME}/webminitwitimage:latest
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - webserver_logs:/app/logs
    networks:
      - minitwit-network
    logging: *syslog_logging

  # --- NEW MONITORING SERVICES ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - minitwit-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_cloud_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    restart: unless-stopped
    logging: *syslog_logging

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    networks:
      - minitwit-network
    volumes:
      - grafana_cloud_data:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    restart: unless-stopped
    logging: *syslog_logging

  discordbot:
    image: ${DOCKER_USERNAME}/discordbotimage:latest
    environment:
      - MONGO_URI=${MONGO_URI}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    networks:
      - minitwit-network
    restart: unless-stopped
    logging: *syslog_logging

  central-rsyslog:
    build:
      context: ./monitoring/rsyslog
      dockerfile: Dockerfile
    container_name: central-rsyslog
    restart: unless-stopped
    environment:
      - RSYSLOG_RETENTION_DAYS=7
      - RSYSLOG_CLEANUP_INTERVAL_SECONDS=3600
    ports:
      - "5514:514/tcp"
      - "5514:514/udp"
    networks:
      - minitwit-network
    volumes:
      - rsyslog_data:/var/log/remote

networks:
  minitwit-network:
    driver: bridge

volumes:
  minitwit_cloud_data:
  prometheus_cloud_data:
  grafana_cloud_data:
  webserver_logs:
  rsyslog_data: