services:
  dbserver:
    image: ${DOCKER_USERNAME}/dbminitwitimage:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=test
    networks:
      - minitwit-network
    volumes:
      - minitwit_cloud_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 90s

  webserver:
    image: ${DOCKER_USERNAME}/webminitwitimage:latest
    restart: unless-stopped
    depends_on:
      dbserver:
        condition: service_healthy
    ports:
      - "80:8080"
    environment:
      - MONGO_URI=mongodb://dbserver:27017
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - minitwit-network

  # --- NEW MONITORING SERVICES ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - minitwit-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_cloud_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    networks:
      - minitwit-network
    volumes:
      - grafana_cloud_data:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    restart: unless-stopped

  discordbot:
    image: ${DOCKER_USERNAME}/discordbotimage:latest
    depends_on:
      dbserver:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://dbserver:27017
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    networks:
      - minitwit-network
    restart: unless-stopped

networks:
  minitwit-network:
    driver: bridge

volumes:
  minitwit_cloud_data:
  prometheus_cloud_data:
  grafana_cloud_data: